namespace FSharpIDD

open WebSharper

/// This module is to reduce the dependencies count and to ease possible WebSharper compilation
[<JavaScript>]
module Colour =    
    type RgbColour = {
        R: byte
        G: byte
        B: byte
    }

    type Colour = 
    | Default
    | Rgb of RgbColour

    let createColour red green blue = Rgb {R=red; G=green;B=blue}

    let AliceBlue               = createColour (byte 0xF0) (byte 0xF8) (byte 0xFF)
    let AntiqueWhite            = createColour (byte 0xFA) (byte 0xEB) (byte 0xD7)
    let Aqua                    = createColour (byte 0x00) (byte 0xFF) (byte 0xFF)
    let Aquamarine              = createColour (byte 0x7F) (byte 0xFF) (byte 0xD4)
    let Azure                   = createColour (byte 0xF0) (byte 0xFF) (byte 0xFF)
    let Beige                   = createColour (byte 0xF5) (byte 0xF5) (byte 0xDC)
    let Bisque                  = createColour (byte 0xFF) (byte 0xE4) (byte 0xC4)
    let Black                   = createColour (byte 0x00) (byte 0x00) (byte 0x00)
    let BlanchedAlmond          = createColour (byte 0xFF) (byte 0xEB) (byte 0xCD)
    let Blue                    = createColour (byte 0x00) (byte 0x00) (byte 0xFF)
    let BlueViolet              = createColour (byte 0x8A) (byte 0x2B) (byte 0xE2)
    let Brown                   = createColour (byte 0xA5) (byte 0x2A) (byte 0x2A)
    let BurlyWood               = createColour (byte 0xDE) (byte 0xB8) (byte 0x87)
    let CadetBlue               = createColour (byte 0x5F) (byte 0x9E) (byte 0xA0)
    let Chartreuse              = createColour (byte 0x7F) (byte 0xFF) (byte 0x00)
    let Chocolate               = createColour (byte 0xD2) (byte 0x69) (byte 0x1E)
    let Coral                   = createColour (byte 0xFF) (byte 0x7F) (byte 0x50)
    let CornflowerBlue          = createColour (byte 0x64) (byte 0x95) (byte 0xED)
    let Cornsilk                = createColour (byte 0xFF) (byte 0xF8) (byte 0xDC)
    let Crimson                 = createColour (byte 0xDC) (byte 0x14) (byte 0x3C)
    let Cyan                    = createColour (byte 0x00) (byte 0xFF) (byte 0xFF)
    let DarkBlue                = createColour (byte 0x00) (byte 0x00) (byte 0x8B)
    let DarkCyan                = createColour (byte 0x00) (byte 0x8B) (byte 0x8B)
    let DarkGoldenRod           = createColour (byte 0xB8) (byte 0x86) (byte 0x0B)
    let DarkGray                = createColour (byte 0xA9) (byte 0xA9) (byte 0xA9)
    let DarkGrey                = createColour (byte 0xA9) (byte 0xA9) (byte 0xA9)
    let DarkGreen               = createColour (byte 0x00) (byte 0x64) (byte 0x00)
    let DarkKhaki               = createColour (byte 0xBD) (byte 0xB7) (byte 0x6B)
    let DarkMagenta             = createColour (byte 0x8B) (byte 0x00) (byte 0x8B)
    let DarkOliveGreen          = createColour (byte 0x55) (byte 0x6B) (byte 0x2F)
    let DarkOrange              = createColour (byte 0xFF) (byte 0x8C) (byte 0x00)
    let DarkOrchid              = createColour (byte 0x99) (byte 0x32) (byte 0xCC)
    let DarkRed                 = createColour (byte 0x8B) (byte 0x00) (byte 0x00)
    let DarkSalmon              = createColour (byte 0xE9) (byte 0x96) (byte 0x7A)
    let DarkSeaGreen            = createColour (byte 0x8F) (byte 0xBC) (byte 0x8F)
    let DarkSlateBlue           = createColour (byte 0x48) (byte 0x3D) (byte 0x8B)
    let DarkSlateGray           = createColour (byte 0x2F) (byte 0x4F) (byte 0x4F)
    let DarkSlateGrey           = createColour (byte 0x2F) (byte 0x4F) (byte 0x4F)
    let DarkTurquoise           = createColour (byte 0x00) (byte 0xCE) (byte 0xD1)
    let DarkViolet              = createColour (byte 0x94) (byte 0x00) (byte 0xD3)
    let DeepPink                = createColour (byte 0xFF) (byte 0x14) (byte 0x93)
    let DeepSkyBlue             = createColour (byte 0x00) (byte 0xBF) (byte 0xFF)
    let DimGray                 = createColour (byte 0x69) (byte 0x69) (byte 0x69)
    let DimGrey                 = createColour (byte 0x69) (byte 0x69) (byte 0x69)
    let DodgerBlue              = createColour (byte 0x1E) (byte 0x90) (byte 0xFF)
    let FireBrick               = createColour (byte 0xB2) (byte 0x22) (byte 0x22)
    let FloralWhite             = createColour (byte 0xFF) (byte 0xFA) (byte 0xF0)
    let ForestGreen             = createColour (byte 0x22) (byte 0x8B) (byte 0x22)
    let Fuchsia                 = createColour (byte 0xFF) (byte 0x00) (byte 0xFF)
    let Gainsboro               = createColour (byte 0xDC) (byte 0xDC) (byte 0xDC)
    let GhostWhite              = createColour (byte 0xF8) (byte 0xF8) (byte 0xFF)
    let Gold                    = createColour (byte 0xFF) (byte 0xD7) (byte 0x00)
    let GoldenRod               = createColour (byte 0xDA) (byte 0xA5) (byte 0x20)
    let Gray                    = createColour (byte 0x80) (byte 0x80) (byte 0x80)
    let Grey                    = createColour (byte 0x80) (byte 0x80) (byte 0x80)
    let Green                   = createColour (byte 0x00) (byte 0x80) (byte 0x00)
    let GreenYellow             = createColour (byte 0xAD) (byte 0xFF) (byte 0x2F)
    let HoneyDew                = createColour (byte 0xF0) (byte 0xFF) (byte 0xF0)
    let HotPink                 = createColour (byte 0xFF) (byte 0x69) (byte 0xB4)
    let IndianRed               = createColour (byte 0xCD) (byte 0x5C) (byte 0x5C)
    let Indigo                  = createColour (byte 0x4B) (byte 0x00) (byte 0x82)
    let Ivory                   = createColour (byte 0xFF) (byte 0xFF) (byte 0xF0)
    let Khaki                   = createColour (byte 0xF0) (byte 0xE6) (byte 0x8C)
    let Lavender                = createColour (byte 0xE6) (byte 0xE6) (byte 0xFA)
    let LavenderBlush           = createColour (byte 0xFF) (byte 0xF0) (byte 0xF5)
    let LawnGreen               = createColour (byte 0x7C) (byte 0xFC) (byte 0x00)
    let LemonChiffon            = createColour (byte 0xFF) (byte 0xFA) (byte 0xCD)
    let LightBlue               = createColour (byte 0xAD) (byte 0xD8) (byte 0xE6)
    let LightCoral              = createColour (byte 0xF0) (byte 0x80) (byte 0x80)
    let LightCyan               = createColour (byte 0xE0) (byte 0xFF) (byte 0xFF)
    let LightGoldenRodYellow    = createColour (byte 0xFA) (byte 0xFA) (byte 0xD2)
    let LightGray               = createColour (byte 0xD3) (byte 0xD3) (byte 0xD3)
    let LightGrey               = createColour (byte 0xD3) (byte 0xD3) (byte 0xD3)
    let LightGreen              = createColour (byte 0x90) (byte 0xEE) (byte 0x90)
    let LightPink               = createColour (byte 0xFF) (byte 0xB6) (byte 0xC1)
    let LightSalmon             = createColour (byte 0xFF) (byte 0xA0) (byte 0x7A)
    let LightSeaGreen           = createColour (byte 0x20) (byte 0xB2) (byte 0xAA)
    let LightSkyBlue            = createColour (byte 0x87) (byte 0xCE) (byte 0xFA)
    let LightSlateGray          = createColour (byte 0x77) (byte 0x88) (byte 0x99)
    let LightSlateGrey          = createColour (byte 0x77) (byte 0x88) (byte 0x99)
    let LightSteelBlue          = createColour (byte 0xB0) (byte 0xC4) (byte 0xDE)
    let LightYellow             = createColour (byte 0xFF) (byte 0xFF) (byte 0xE0)
    let Lime                    = createColour (byte 0x00) (byte 0xFF) (byte 0x00)
    let LimeGreen               = createColour (byte 0x32) (byte 0xCD) (byte 0x32)
    let Linen                   = createColour (byte 0xFA) (byte 0xF0) (byte 0xE6)
    let Magenta                 = createColour (byte 0xFF) (byte 0x00) (byte 0xFF)
    let Maroon                  = createColour (byte 0x80) (byte 0x00) (byte 0x00)
    let MediumAquaMarine        = createColour (byte 0x66) (byte 0xCD) (byte 0xAA)
    let MediumBlue              = createColour (byte 0x00) (byte 0x00) (byte 0xCD)
    let MediumOrchid            = createColour (byte 0xBA) (byte 0x55) (byte 0xD3)
    let MediumPurple            = createColour (byte 0x93) (byte 0x70) (byte 0xDB)
    let MediumSeaGreen          = createColour (byte 0x3C) (byte 0xB3) (byte 0x71)
    let MediumSlateBlue         = createColour (byte 0x7B) (byte 0x68) (byte 0xEE)
    let MediumSpringGreen       = createColour (byte 0x00) (byte 0xFA) (byte 0x9A)
    let MediumTurquoise         = createColour (byte 0x48) (byte 0xD1) (byte 0xCC)
    let MediumVioletRed         = createColour (byte 0xC7) (byte 0x15) (byte 0x85)
    let MidnightBlue            = createColour (byte 0x19) (byte 0x19) (byte 0x70)
    let MintCream               = createColour (byte 0xF5) (byte 0xFF) (byte 0xFA)
    let MistyRose               = createColour (byte 0xFF) (byte 0xE4) (byte 0xE1)
    let Moccasin                = createColour (byte 0xFF) (byte 0xE4) (byte 0xB5)
    let NavajoWhite             = createColour (byte 0xFF) (byte 0xDE) (byte 0xAD)
    let Navy                    = createColour (byte 0x00) (byte 0x00) (byte 0x80)
    let OldLace                 = createColour (byte 0xFD) (byte 0xF5) (byte 0xE6)
    let Olive                   = createColour (byte 0x80) (byte 0x80) (byte 0x00)
    let OliveDrab               = createColour (byte 0x6B) (byte 0x8E) (byte 0x23)
    let Orange                  = createColour (byte 0xFF) (byte 0xA5) (byte 0x00)
    let OrangeRed               = createColour (byte 0xFF) (byte 0x45) (byte 0x00)
    let Orchid                  = createColour (byte 0xDA) (byte 0x70) (byte 0xD6)
    let PaleGoldenRod           = createColour (byte 0xEE) (byte 0xE8) (byte 0xAA)
    let PaleGreen               = createColour (byte 0x98) (byte 0xFB) (byte 0x98)
    let PaleTurquoise           = createColour (byte 0xAF) (byte 0xEE) (byte 0xEE)
    let PaleVioletRed           = createColour (byte 0xDB) (byte 0x70) (byte 0x93)
    let PapayaWhip              = createColour (byte 0xFF) (byte 0xEF) (byte 0xD5)
    let PeachPuff               = createColour (byte 0xFF) (byte 0xDA) (byte 0xB9)
    let Peru                    = createColour (byte 0xCD) (byte 0x85) (byte 0x3F)
    let Pink                    = createColour (byte 0xFF) (byte 0xC0) (byte 0xCB)
    let Plum                    = createColour (byte 0xDD) (byte 0xA0) (byte 0xDD)
    let PowderBlue              = createColour (byte 0xB0) (byte 0xE0) (byte 0xE6)
    let Purple                  = createColour (byte 0x80) (byte 0x00) (byte 0x80)
    let RebeccaPurple           = createColour (byte 0x66) (byte 0x33) (byte 0x99)
    let Red                     = createColour (byte 0xFF) (byte 0x00) (byte 0x00)
    let RosyBrown               = createColour (byte 0xBC) (byte 0x8F) (byte 0x8F)
    let RoyalBlue               = createColour (byte 0x41) (byte 0x69) (byte 0xE1)
    let SaddleBrown             = createColour (byte 0x8B) (byte 0x45) (byte 0x13)
    let Salmon                  = createColour (byte 0xFA) (byte 0x80) (byte 0x72)
    let SandyBrown              = createColour (byte 0xF4) (byte 0xA4) (byte 0x60)
    let SeaGreen                = createColour (byte 0x2E) (byte 0x8B) (byte 0x57)
    let SeaShell                = createColour (byte 0xFF) (byte 0xF5) (byte 0xEE)
    let Sienna                  = createColour (byte 0xA0) (byte 0x52) (byte 0x2D)
    let Silver                  = createColour (byte 0xC0) (byte 0xC0) (byte 0xC0)
    let SkyBlue                 = createColour (byte 0x87) (byte 0xCE) (byte 0xEB)
    let SlateBlue               = createColour (byte 0x6A) (byte 0x5A) (byte 0xCD)
    let SlateGray               = createColour (byte 0x70) (byte 0x80) (byte 0x90)
    let SlateGrey               = createColour (byte 0x70) (byte 0x80) (byte 0x90)
    let Snow                    = createColour (byte 0xFF) (byte 0xFA) (byte 0xFA)
    let SpringGreen             = createColour (byte 0x00) (byte 0xFF) (byte 0x7F)
    let SteelBlue               = createColour (byte 0x46) (byte 0x82) (byte 0xB4)
    let Tan                     = createColour (byte 0xD2) (byte 0xB4) (byte 0x8C)
    let Teal                    = createColour (byte 0x00) (byte 0x80) (byte 0x80)
    let Thistle                 = createColour (byte 0xD8) (byte 0xBF) (byte 0xD8)
    let Tomato                  = createColour (byte 0xFF) (byte 0x63) (byte 0x47)
    let Turquoise               = createColour (byte 0x40) (byte 0xE0) (byte 0xD0)
    let Violet                  = createColour (byte 0xEE) (byte 0x82) (byte 0xEE)
    let Wheat                   = createColour (byte 0xF5) (byte 0xDE) (byte 0xB3)
    let White                   = createColour (byte 0xFF) (byte 0xFF) (byte 0xFF)
    let WhiteSmoke              = createColour (byte 0xF5) (byte 0xF5) (byte 0xF5)
    let Yellow                  = createColour (byte 0xFF) (byte 0xFF) (byte 0x00)
    let YellowGreen             = createColour (byte 0x9A) (byte 0xCD) (byte 0x32)